export enum PermissionEnum {
    AIRPORT_READ                          = 'airport read',
    AIRPORT_WRITE                         = 'airport write',
    FLIGHT_LOG_READ                       = 'flight_log read',
    FLIGHT_LOG_WRITE                      = 'flight_log write',
    GROUP_READ                            = 'group read',
    GROUP_WRITE                           = 'group write',
    MAKE_MODEL_READ                       = 'make_model read',
    MAKE_MODEL_WRITE                      = 'make_model write',
    PERMISSION_READ                       = 'permission read',
    PILOT_READ                            = 'pilot read',
    PILOT_WRITE                           = 'pilot write',
    REGISTRATION_READ                     = 'registration read',
    REGISTRATION_WRITE                    = 'registration write',
    SIGNIFICANT_EVENT_READ                = 'significant_event read',
    SIGNIFICANT_EVENT_WRITE               = 'significant_event write',
    SUMMARY                               = 'summary',
    USER_READ                             = 'user read',
    USER_WRITE                            = 'user write',
    AIRPORT_SYNC                          = 'airport sync',
    FLIGHT_LOG_SYNC                       = 'flight_log sync',
    MAKE_MODEL_SYNC                       = 'make_model sync',
    PILOT_SYNC                            = 'pilot sync',
    REGISTRATION_SYNC                     = 'registration sync',
    SIGNIFICANT_EVENT_SYNC                = 'significant_event sync'
}
